### ISSUE TITLE
UX suggestion: Better sorting of campaigns

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-dapp#133]
At the moment when you log in an advertiser account, the default sorting of campaigns is by **"Status"** - From "Expired" to "Active" in a chronological order from oldest to newest. 
![Screenshot 2019-08-07 at 11 01 56](https://user-images.githubusercontent.com/15030734/62606022-fd773800-b903-11e9-9a2b-acf1802230b8.png)

1. Chronological order, no matter what the sorting option, should always be "From most recent to oldest" - active users want to know what's happening at the moment w. their campaigns, so the most recent ones should always stay on top of the screen. At the moment in order to see my only active campaign I should scroll to the very bottom. 

2. This actually works properly when Sorting option is "Created", so I guess if we just make this option default it will be much better.
![Screenshot 2019-08-07 at 11 09 39](https://user-images.githubusercontent.com/15030734/62606078-15e75280-b904-11e9-8d2c-0f93d5523448.png)

**Comment by IvoPaunov** [comment]
1a3edb5fcf1a445942c548bd5f9d166aceb2017d
