### ISSUE TITLE
Error creating Campaign: [object Object]

### ISSUE THREAD

**Issue by t1m3c** [AdExNetwork/adex-dapp#25]
Error, when trying to add campagin Error creating Campaign: [object Object]
Tested on Brave and Chrome.
Screenshot: https://gyazo.com/2999ed21144e2d47c7ed1d83f293000f

**Comment by IvoPaunov** [comment]
Thank you. Fixed with [adex-node update](https://github.com/AdExNetwork/adex-node/commit/484601a8c282addc3a9dee8c5a843919b829165b).
