### ISSUE TITLE
Campaign editor in advertiser mode

### ISSUE THREAD

**Issue by ahaghdan** [AdExNetwork/adex-dapp#26]
I can't save changes to a campaign or archive a campaign in advertiser mode It is only possible to create new campaigns!

v.2.1.5-beta

**Comment by IvoPaunov** [comment]
Thank you, it was bug with updated mongodb driver in [adex-node](https://github.com/AdExNetwork/adex-node) and it is [fixed](https://github.com/AdExNetwork/adex-node/commit/aef89595fe01b6d6cd8033432e9c0581d86f08ce) now.
