### ISSUE TITLE
Error creating AdUnit

### ISSUE THREAD

**Issue by ahaghdan** [AdExNetwork/adex-dapp#27]
I am unable to create a new ad unit in advertiser mode, i tried to create new ad unit standalone or inside a campaign none of them work. It is a bit annoying the error says "Error creating AdUnit:[object Object]. I think you should have some unit tests that check these essential functions upon every release to prevent this from getting through to users.

v.2.1.5-beta

**Comment by IvoPaunov** [comment]
Yes, we should have unit tests and soon there will be. As for the bug until the next release (maybe I'll push it today) try create adUnit but add some tags. For some reason the validation does not work in production.

Thank you very much

**Comment by IvoPaunov** [comment]
Fixed in v2.1.6-beta
