### ISSUE TITLE
Visualisation of images on the Publisher side distorts image ratio

### ISSUE THREAD

**Issue by dmngdsm** [AdExNetwork/adex-dapp#53]
When creating 728x90 ad slot I have no problems uploading 728x90 fallback and avatar images, but when I open the dashboard the images in slots overview and in each slot are stretched. When I open an image it looks cropped. 

This might be a problem for publishers for they won't be able to tell differences between similar adslots and preview their visuals. 

![screen shot 2019-02-14 at 14 31 17](https://user-images.githubusercontent.com/15030734/52787096-7a1c0e80-3065-11e9-9145-5ccbf4299fcc.png)
![screen shot 2019-02-14 at 14 30 57](https://user-images.githubusercontent.com/15030734/52787097-7a1c0e80-3065-11e9-8528-d10478b588f7.png)

**Comment by IvoPaunov** [comment]
Thanks,  It will be  fixed in v4 release.
