### ISSUE TITLE
Rename tab heading from "AdEx dApp" to "AdEx Platform" 

### ISSUE THREAD

**Issue by Dylanoshi** [AdExNetwork/adex-dapp#67]
in concert with our repositioning to a 'platform'

**Comment by IvoPaunov** [comment]
Duplicate of #51

**Comment by IvoPaunov** [comment]
[Done](https://github.com/AdExNetwork/adex-dapp/commit/c8c0e42ba8b61e398055113559c8006c05a8dd32)
