### ISSUE TITLE
Authenticate with MetaMask

### ISSUE THREAD

**Issue by theman480** [AdExNetwork/adex-dapp#9]
So I'm using AdEx dapp on Android with Firefox app, when I sign in metamask extension nothing happens on AdEx.
Is there any button to tap? I mean the AdEx dapp is not showing proprely on my device and I can't zoom out the page.

**Comment by IvoPaunov** [comment]
Currently the dApp is not supposed to work on mobile browsers. I'll inform you when this functionality is ready.
Thank you for the report!

**Comment by martinyakimov25** [comment]
Hello,
When you click "Connect to MetaMask", you should go to MetaMask tab and type your password. Then click it again. You will see your address and balance. Click "Authenticate address" and go to MetaMask again and click Sign button.
Engoy!

**Comment by IvoPaunov** [comment]
Hi, I have idea how it should work but there was a some problem with MetaMask communication.  The other thing was that the design was not responsive and there was no point of wasting time for this. Now the design is almost ready for mobile  so I'll check that soon.
Thanks
